name: Report a bug / issue
description: Report an issue with the Energi Data Service integration
labels: ["bug"]
assignees:
  - MTrab
body:
  - type: markdown
    attributes:
      value: |
        Note:
        This issue form is for reporting bugs only!
        KEEP THE LANGUAGE AT ENGLISH PLEASE!

        PLEASE MAKE SURE YOU HAVE INSTALLED THE LATEST VERSION BEFORE SUBMITTING A NEW ISSUE!
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the issue
      description: >-
        Describe the issue you are experiencing here.
        Describe what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version of Home Assistant Core has the issue?
      placeholder: core-
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
  - type: input
    attributes:
      label: What was the last working version of Home Assistant Core?
      placeholder: core-
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        Can be found in: [Settings ⇒ System ⇒ Repairs ⇒ Three Dots in Upper Right ⇒ System information](https://my.home-assistant.io/redirect/system_health/).

        [![Open your Home Assistant instance and show the system information.](https://my.home-assistant.io/badges/system_health.svg)](https://my.home-assistant.io/redirect/system_health/)
      options:
        - Home Assistant OS
        - Home Assistant Container
        - Home Assistant Supervised
        - Home Assistant Core
  - type: markdown
    attributes:
      value: |
        # Details
  - type: upload
    attributes:
      label: Diagnostics file
      description: >-
        This integration provides the ability to [download diagnostic data](https://www.home-assistant.io/docs/configuration/troubleshooting/#download-diagnostics).

        **Please upload the diagnostics JSON file here instead of copy-pasting its content.**

        It generally allows pinpointing defects and thus resolving issues faster.
  - type: textarea
    attributes:
      label: If you could not provide diagnostics, explain why
      description: >-
        If you are unable to provide the diagnostics file (for example because you cannot add the integration),
        explain why here. Otherwise leave this field empty.
  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: txt
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.
