"""Valid Charge Owners for Energi Data Service connector."""

CHARGEOWNERS = [
    "TREFOR El-net A/S",
    "FLOW Elnet A/S",
    "Dinel A/S",
    "Videbæk Elnet A/S",
    "Vores Elnet A/S",
    "N1 A/S - 344",
    "RAH Net A/S",
    "Ikast El Net A/S",
    "Konstant Net A/S - 245",
    "Konstant Net A/S - 151",
    "Cerius A/S",
    "Radius Elnet A/S",
    "TREFOR El-Net Øst A/S",
    "Elektrus A/S",
    "Ravdex A/S",
    "NKE-Elnet A/S",
    "Nakskov Elnet A/S",
    "Midtfyns Elforsyning A.m.b.A",
    "Zeanet A/S",
    "L-Net A/S",
    "Sunds Elforsyning",
    "Aal El-Net A M B A",
    "Elnet Midt A/S",
    "El-net Kongerslev A/S",
]
