"""Valid Charge Owners for Energi Data Service connector."""

CHARGEOWNERS = {
    "Radius": {
        "gln": "5790000705689",
        "company": "Radius Elnet A/S",
        "type": ["DT_C_01"],
        "note": ["Nettarif C time"],
    },
    "Radius": {
        "gln": "5790000705689",
        "company": "Radius Elnet A/S",
        "type": ["DT_B_02"],
        "note": ["Nettarif B lav time"],
    },
    "RAH": {
        "gln": "5790000681327",
        "company": "RAH Net A/S",
        "type": ["RAH-C"],
        "note": ["Nettarif C time"],
    },
    "Konstant": {
        "gln": "5790000704842",
        "company": "Konstant Net A/S - 151",
        "type": ["151-NT01T"],
        "note": ["Nettarif C time"],
    },
    "Cerius": {
        "gln": "5790000705184",
        "company": "Cerius A/S",
        "type": ["30TR_C_ET"],
        "note": ["Nettarif C time"],
    },
    "N1": {
        "gln": "5790001089030",
        "company": "N1 A/S - 131",
        "type": ["CD", "CD R"],
        "note": ["Nettarif C"],
    },
    "N1 Randers": {
        "gln": "5790000681372",
        "company": "N1 Randers A/S",
        "type": ["CD"],
        "note": ["Nettarif C"],
    },
    "Dinel": {
        "gln": "5790000610099",
        "company": "Dinel A/S",
        "type": ["TCL>100_02"],
        "note": ["Nettarif C time"],
    },
    "TREFOR El-net": {
        "gln": "5790000392261",
        "company": "TREFOR El-net A/S",
        "type": ["C"],
        "note": ["Nettarif C time"],
    },
    "TREFOR El-net Øst": {
        "gln": "5790000706686",
        "company": "TREFOR El-net Øst A/S",
        "type": ["46"],
        "note": ["Nettarif C time"],
    },
    "Elektrus": {
        "gln": "5790000836239",
        "company": "Elektrus A/S",
        "type": ["6000091"],
        "note": ["Nettarif C time"],
    },
    "Elnet Midt": {
        "gln": "5790001100520",
        "company": "Elnet Midt A/S",
        "type": ["T3002"],
        "note": ["Nettarif C"],
    },
    "Hurup Elværk Net": {
        "gln": "5790000610839",
        "company": "Hurup Elværk Net A/S",
        "type": ["HEV-NT-01"],
        "note": ["Nettarif"],
    },
    "Veksel": {
        "gln": "5790001088217",
        "company": "Veksel A/S",
        "type": ["NT-10"],
        "note": ["Nettarif C time  NT-10"],
    },
    "Vores Elnet": {
        "gln": "5790000610976",
        "company": "Vores Elnet A/S",
        "type": ["TNT1009"],
        "note": ["Nettarif C time"],
    },
    "Netselskabet Elværk": {
        "gln": "5790000681075",
        "company": "Netselskabet Elværk A/S - 042",
        "type": ["0NCFF"],
        "note": ["Nettarif C Flex"],
    },
    "Nord Energi Net": {
        "gln": "5790000610877",
        "company": "Nord Energi Net A/S",
        "type": ["TA031U200"],
        "note": ["Nettarif C"],
    },
    "Nordvestjysk Elforsyning (NOE Net)": {
        "gln": "5790000395620",
        "company": "NOE Net A/S",
        "type": ["Net C"],
        "note": ["Nettarif C"],
    },
    "Ikast El Net": {
        "gln": "5790000682102",
        "company": "Ikast El Net A/S",
        "type": ["IEV-NT-01", "IEV-NT-11"],
        "note": ["Nettarif C time", "Transport - Overordnet net"],
    },
    "FLOW Elnet": {
        "gln": "5790000392551",
        "company": "FLOW Elnet A/S",
        "type": ["FE2 NT-01"],
        "note": ["Nettarif C time"],
    },
    "Elinord": {
        "gln": "5790001095277",
        "company": "Elinord A/S",
        "type": ["43300"],
        "note": ["Transportbetaling, eget net C"],
    },
    "Hammel Elforsyning Net": {
        "gln": "5790001090166",
        "company": "Hammel Elforsyning Net A/S",
        "type": ["50001"],
        "note": ["Overliggende net"],
    },
    "El-net Kongerslev": {
        "gln": "5790002502699",
        "company": "El-net Kongerslev A/S",
        "type": ["K_22100"],
        "note": ["Nettarif C"],
    },
    "Ravdex": {
        "gln": "5790000836727",
        "company": "Ravdex A/S",
        "type": ["NT-C"],
        "note": ["Nettarif C time"],
    },
    "Tarm Elværk Net": {
        "gln": "5790000706419",
        "company": "Tarm Elværk Net A/S",
        "type": ["TEV-NT-01"],
        "note": ["Nettarif C"],
    },
    "Zeanet": {
        "gln": "5790001089375",
        "company": "Zeanet A/S",
        "type": ["43110"],
        "note": ["Nettarif C time"],
    },
    "NKE-Elnet": {
        "gln": "5790001088231",
        "company": "NKE-Elnet A/S",
        "type": ["94TR_C_ET"],
        "note": ["Nettarif C time"],
    },
    "L-Net": {
        "gln": "5790001090111",
        "company": "L-Net A/S",
        "type": ["4010"],
        "note": ["Nettarif C time"],
    },
    "Midtfyns Elforsyning": {
        "gln": "5790001089023",
        "company": "Midtfyns Elforsyning A.m.b.A",
        "type": ["TNT15000"],
        "note": ["Nettarif C Flex"],
    },
}
